CREATE TABLE ticket_assignment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id UUID NOT NULL REFERENCES tickets(id),
    actor_id UUID NOT NULL REFERENCES app_users(id),
    previous_assignee_id UUID REFERENCES app_users(id),
    assignee_id UUID REFERENCES app_users(id),
    idempotency_key VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ticket_assignment_events_ticket_key UNIQUE (ticket_id, idempotency_key)
);

CREATE INDEX idx_ticket_assignment_events_ticket ON ticket_assignment_events(ticket_id, created_at);
